### Task
The dataset is a 2D numpy array of 10 students and 5 subjects, with random integer scores from 60 to 100.

#### Calculate useful stats:
Answer these questions:
<ol>
  <li>What is the average score per student?</li>
  <li>What is the average score per subject?</li>
  <li>What is the highest and lowest score in the whole class?</li>
  <li>Which student got the highest total score?</li>
</ol>

In [ ]:
# dataset
import numpy as np 

np.random.seed(0) # reproducible results
grades = np.random.randint(50, 100, size=(10, 5))
print(grades)

[[94 97 50 53 53]
 [89 59 69 71 86]
 [73 56 74 74 62]
 [51 88 89 73 96]
 [74 67 87 75 63]
 [58 59 70 66 55]
 [65 97 50 68 85]
 [74 99 79 69 69]
 [64 89 82 51 59]
 [82 81 60 73 85]]


In [2]:
# get average score per student
i = 0
for student in grades:
  ave_grade_per_student = np.average(student)
  i += 1
  print(f"Average of student {i}: ", ave_grade_per_student)

Average of student 1:  69.4
Average of student 2:  74.8
Average of student 3:  67.8
Average of student 4:  79.4
Average of student 5:  73.2
Average of student 6:  61.6
Average of student 7:  73.0
Average of student 8:  78.0
Average of student 9:  69.0
Average of student 10:  76.2


In [ ]:
# get average score per subject

col = 0
subj_count = 1
while col < 5:
  subj_scores = grades[:, col]
  col += 1

  print(f"Average score of subject {subj_count}: ", np.average(subj_scores))
  subj_count += 1

Average score of subject 1:  72.4
Average score of subject 2:  79.2
Average score of subject 3:  71.0
Average score of subject 4:  67.3
Average score of subject 5:  71.3


In [4]:
# highest and lowest
print("Highest score: ", np.max(grades))
print("Lowest score: ", np.min(grades))

Highest score:  99
Lowest score:  50


In [23]:
# student highest total score

for rows in grades:
  total_scores = np.array([np.sum(rows)])

  print(type(total_scores))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
