In [1]:
# package import
import numpy as np

Here, we will demonstrate the superiority of np.array than native python lists.

Say, we are given a list and we want to multiply each number in the list by 2. For native python lists, it will just double it like this

<code>[1, 2, 3, 4, 1, 2, 3, 4]</code>

In [2]:
arr = np.array([1, 2, 3, 4])
mult_by_2 = arr * 2

print(mult_by_2)

[2 4 6 8]


<ul>
  <li>To verify the data type of variables, use the <code>type()</code> function</li>
  <li>To verify the number of dimensions an array has, use <code>arr.ndim</code></li>
  <li>To know the shape of the array, use <code>.shape</code>: returns a tuple <code>(layers, rows, columns)</code></li>
</ul>

# Multidimensional indexing

Form a 3 letter word with string concatination from the array

In [3]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '_']]])

print(array[2, 2, 1])

print("Word: " + array[0,0,2] + array[0,0,0] + array[2,0,1])

Z
Word: CAT


# Slicing
### Row selection

In [4]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# array[start:end:step]
print("First row: ")
print(array[0])

# for range
# [inclusive: exclusive]
print("Rows 1 - 3: ")
print(array[0:3])

# with step
print("Every second row: ")
print(array[::2])

First row: 
[1 2 3 4]
Rows 1 - 3: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Every second row: 
[[ 1  2  3  4]
 [ 9 10 11 12]]


# Slicing
### Column Selection

In [5]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

print("Col 1: ")
print(array[:, 0])

print("Col 1-3: ")
print(array[:, 0:3])

print("First 2 rows and first 2 cols:")
print(array[0:2, 0:2])

Col 1: 
[ 1  5  9 13]
Col 1-3: 
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
First 2 rows and first 2 cols:
[[1 2]
 [5 6]]


# Arithmetic

In [6]:
# Scalar Arithmetic
array = np.array([1, 2, 3])
print(array + 1)

[2 3 4]


In [7]:
# Vector math functions
array = np.array([1.25, 2.67, 3.31])

print("Squareroot of each num: ", np.sqrt(array))
print("Round each: ", np.round(array)) #.ceil round up .floor round down

Squareroot of each num:  [1.11803399 1.63401346 1.81934054]
Round each:  [1. 3. 3.]


Exercise:
Given the radii, convert it to an area of a circle

In [8]:
radii = np.array([1, 2, 3])

print("Areas: ")
print(np.pi * (radii ** 2))

Areas: 
[ 3.14159265 12.56637061 28.27433388]


In [9]:
# Element-wise arithmetic
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 * array2)

[ 4 10 18]


In [10]:
# Comparison operators

scores = np.array([91, 55, 100, 73, 82, 64])

# see if someone passed: >= 60
print(scores >= 60)

# any score less than 60 will automatically be zero
scores[scores < 60] = 0
print(scores)

[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


# Broadcasting
Broadcasting allows numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape

<ul>
  <li>The dimensions have the same size</li>
  <li>One of the dimensions has a size of 1</li>
</ul>

In [11]:
# 1 x 4
arr1 = np.array([[1, 2, 3, 4]])

# 4 x 1
arr2 = np.array([[1], 
                 [2], 
                 [3], 
                 [4]])

print("Shape of arr1: ", arr1.shape)
print("Shape of arr2: ", arr2.shape)

print("Multiplying them together:")
print(arr1 * arr2)

Shape of arr1:  (1, 4)
Shape of arr2:  (4, 1)
Multiplying them together:
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


# Aggregate Functions
Summarizes data and typically return a single value

These include: 
<ul>
  <li><code>np.sum()</code></li>
  <li><code>np.mean()</code></li>
  <li><code>np.median()</code></li>
  <li><code>np.std()</code></li>
  <li><code>np.var()</code></li>
  <li><code>np.min()</code></li>
  <li><code>np.max()</code></li>
  <li><code>np.argmin()</code></li>
</ul>

Look at numpy documentation for more...

In [12]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print("Sum of the numbers in array: ", np.sum(arr))
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))

Sum of the numbers in array:  55
Mean:  5.5
Median:  5.5


# Filtering
Process of selecting elements from an array that match a given condition

In [13]:
age_in_class = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                         [39, 22, 15, 99, 18, 19, 20, 21]])

# Get teenagers
teens = age_in_class[age_in_class <= 18]
print(teens)

[17 16 18 15 18]
