### Weather Data Simulation
A 5x7 numpy array that represents temperatures in degrees Celsius for 5 days and 7 different city zones.

Questions to solve:
<ul>
  <li>What is the average temperature per day?</li>
  <li>What is the highest and lowest temperature recorded in the entire dataset?</li>
  <li>Which day had the highest average temperature?</li>
  <li>Replace all temperatures below 25C with exactly 25 (this is for sensor calibration)</li>
  <li>Add 2C to all temperatures on the last day (simulation for heat waves)</li>
  <li>Create a boolean mask that shows which cells are above 35C</li>
  <li>Transpose the array and explain what that represents</li>
</ul>

In [1]:
# create dataset
import numpy as np

np.random.seed(1)
temps = np.random.randint(20, 41, size=(5, 7))
print(temps)

[[25 31 32 28 29 31 25]
 [35 20 36 21 32 27 33]
 [26 38 40 25 38 40 31]
 [30 34 38 24 29 37 20]
 [33 29 29 27 21 20 37]]


In [2]:
# average temps per day
i = 1
for rows in temps:
  ave_temps = np.average(rows)
  print(f"Day {i}: {round(ave_temps, 2)}C")
  i += 1

Day 1: 28.71C
Day 2: 29.14C
Day 3: 34.0C
Day 4: 30.29C
Day 5: 28.0C


In [3]:
# highest and lowest temp recorded in entire dataset
print(f"Highest recorded temperature: {round(np.max(temps), 2)}C")
print(f"Lowest recorded temperature: {round(np.min(temps), 2)}C")

Highest recorded temperature: 40C
Lowest recorded temperature: 20C


In [ ]:
# day with highest average temp

# axis=1 - columns
# axis=0 - rows

arr_ave = np.mean(temps, axis=1)
indices = np.argsort(arr_ave)[::-1]

for i in indices:
  print(f"Day {i + 1}: {round(arr_ave[i], 2)}C")


Day 3: 34.0C
Day 4: 30.29C
Day 2: 29.14C
Day 1: 28.71C
Day 5: 28.0C
