### Task
The dataset is a 2D numpy array of 10 students and 5 subjects, with random integer scores from 60 to 100.

#### Calculate useful stats:
Answer these questions:
<ol>
  <li>What is the average score per student?</li>
  <li>What is the average score per subject?</li>
  <li>What is the highest and lowest score in the whole class?</li>
  <li>Which student got the highest total score?</li>
</ol>

In [2]:
# dataset
import numpy as np 

np.random.seed(0) # reproducible results
grades = np.random.randint(50, 100, size=(10, 5))
print(grades)

[[94 97 50 53 53]
 [89 59 69 71 86]
 [73 56 74 74 62]
 [51 88 89 73 96]
 [74 67 87 75 63]
 [58 59 70 66 55]
 [65 97 50 68 85]
 [74 99 79 69 69]
 [64 89 82 51 59]
 [82 81 60 73 85]]


In [3]:
# get average score per student
i = 0
for student in grades:
  ave_grade_per_student = np.average(student)
  i += 1
  print(f"Average of student {i}: ", ave_grade_per_student)

Average of student 1:  69.4
Average of student 2:  74.8
Average of student 3:  67.8
Average of student 4:  79.4
Average of student 5:  73.2
Average of student 6:  61.6
Average of student 7:  73.0
Average of student 8:  78.0
Average of student 9:  69.0
Average of student 10:  76.2


In [4]:
# get average score per subject

col = 0
subj_count = 1
while col < 5:
  subj_scores = grades[:, col]
  col += 1

  print(f"Average score of subject {subj_count}: ", np.average(subj_scores))
  subj_count += 1

Average score of subject 1:  72.4
Average score of subject 2:  79.2
Average score of subject 3:  71.0
Average score of subject 4:  67.3
Average score of subject 5:  71.3


In [5]:
# highest and lowest
print("Highest score: ", np.max(grades))
print("Lowest score: ", np.min(grades))

Highest score:  99
Lowest score:  50


In [6]:
# student highest total score

# np.argmax() returns index
# axis=0 - vertical
# axis=1 - horizontal

total_score = grades.sum(axis=1)
student = np.argmax(total_score)
highest_score = np.max(total_score)
print(f"Student {student} has the highest total score of {highest_score}")

Student 3 has the highest total score of 397


### Bonus Tasks
<ul>
  <li>add 5 extra credit points to every grade but cap at 100</li>
  <li>sort students by their total score (highest to lowest)</li>
  <li>find all students who scored below 70 in any subject</li>
  <li>reshape the array to (5,10) -- what does that represent?</li>
</ul>

In [7]:
# add 5 extra credit points to every grade stop at 100
extra_credit_grades = grades + 5

extra_credit_grades[extra_credit_grades > 100] = 100
print(extra_credit_grades)

[[ 99 100  55  58  58]
 [ 94  64  74  76  91]
 [ 78  61  79  79  67]
 [ 56  93  94  78 100]
 [ 79  72  92  80  68]
 [ 63  64  75  71  60]
 [ 70 100  55  73  90]
 [ 79 100  84  74  74]
 [ 69  94  87  56  64]
 [ 87  86  65  78  90]]


In [8]:
# sort students by their total score high -> low
total_score = grades.sum(axis=1)
sorted = np.argsort(total_score)[::-1]

for i in sorted:
  print(f"Student {i + 1}: {total_score[i]}")


Student 4: 397
Student 8: 390
Student 10: 381
Student 2: 374
Student 5: 366
Student 7: 365
Student 1: 347
Student 9: 345
Student 3: 339
Student 6: 308


In [16]:
# finding all students who scored below 70

# Output: student 1
#         student 2
print("Students who scored below 70 in any subject: ")

for i, row in enumerate(grades):
  if np.any(row < 70):
    print(f"Student {i + 1}")


Students who scored below 70 in any subject: 
Student 1
Student 2
Student 3
Student 4
Student 5
Student 6
Student 7
Student 8
Student 9
Student 10


In [17]:
# Reshape
reshaped_grades = grades.reshape(5, 10)

print(reshaped_grades)

[[94 97 50 53 53 89 59 69 71 86]
 [73 56 74 74 62 51 88 89 73 96]
 [74 67 87 75 63 58 59 70 66 55]
 [65 97 50 68 85 74 99 79 69 69]
 [64 89 82 51 59 82 81 60 73 85]]


The reshaped grades array means that the scores per subject are the rows and the columns are the scores of each student